### ISSUE TITLE
List total number of reports at the bottom of menus

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#10]
At bottom full number of reports on the list should be stated outright like "Reports 1-10 of 265" or "1-10 of 265 reports". This is better than just the number of pages, which requires that users do a maths problem to know how many reports.
**This is a bigger deal, because currently the react-table component doesn't support this feature, we should manually implement it. I'll keep it on my schedule, but it's not a priority at the moment.**

**Comment by JoshBone** [comment]
With the new type of filter there is actually a big free space on the right side which makes it fairly easy to add the total number of reports here. 

I've added a dynamic text to the row, see it on the right side where the filter button is:
https://admin.test.deqar.eu/reports

Do you think it will be okay like this? 
I included an indicator if the number of reports in the table are total or filtered.

**Comment by Gyukat** [comment]
This seems an okay solution for now.  In general, Colin and I still find that there is a lot of "balast" (i.e. extra space and visual elements) around the screen.  The actual records start very low on the page.  We can discuss more when you get back.

**Comment by JoshBone** [comment]
https://app.conceptboard.com/board/8no2-2ixh-2gn7-2qzs-dkxq 
Here you can add comments to the design, so you can just mark where and what should be changed.
