### ISSUE TITLE
MyReport Menu should be elided with Dashboard View

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#12]
We think that there is no need for a separate Dashboard as it more or less replicates the MyReport functionality.  So: 

 - MyReports can have the stats at the top that are currently in Dashboard.
 - MyReports should contain all reports that the agency has submitted (not the ones they originally created).  These are the ones the agency can actually edit.
 - Add accordion feature to MyReports record entries.  For now, just list the flags and their justifications inside the accordion.
 - The MyReports can become the top side menu option under MyData and can become the start page.

_Colin and I realised that there is a problem when we define access to reports because sometimes agencies have reports submitted through proxies, but others submitted by themselves.  This is fine; the agencies should only have edit access through MyReports to the ones they submit._

_Related to this, we realise that Agencies may use CSV/API with their local ID to overwrite reports submitted already by proxies.  We should discuss, but probably local IDs should be hooked in our system to BOTH a creator and a submitter...so they can be used only by the same combination in order to overwrite._

**Comment by JoshBone** [comment]
> Colin and I realised that there is a problem when we define access to reports because sometimes agencies have reports submitted through proxies, but others submitted by themselves. This is fine; the agencies should only have edit access through MyReports to the ones they submit.

So does this mean, that reports which are about the agency should be displayed in the MyReports, but if they were submitted by a proxy it shouldn't be editable?

**Comment by Gyukat** [comment]
No, only those submitted by the institution should be viewed and editable.  All others (even those by proxy) can be in the "reference data/reports".  Related to this, an agency should only have edit rights over those that it actually uploaded.

**Comment by Gyukat** [comment]
I completely changed the policy on this!  So, basically:

- an agency can see and edit what it owns.  
- a proxy can see what it has submitted but not edit it.

The MyReports list should reflect this, by showing proxy reports in BOTH places (for the owning and proxy agency) but only the owning agency can edit. Sorry for the confusion.
