### ISSUE TITLE
Browse file problems

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#13]
- if you browse for a file, and then want to cancel the option, it is not possible.
   - _The cancel does not get rid of an existing value as I can see...so we need some sort of delete or erase function._
   - But just to clarify, you want to cancel, if you accidentally selected a file and you rather want to enter a URL. Because otherwise, you should press X on the main form to remove the file and save the record.  _YES_

- When you use the browse, we still get the "file location was not provided" note on the actual page and a yellow flag on the email notification though not in the system.

**Comment by JoshBone** [comment]
Please check...

**Comment by Gyukat** [comment]
The fix is beautiful and works in both new report and edit report.  

I still get a yellow message on submission, though it disappears both times before I could read it, and the email notification says that file location was not provided.

**Comment by JoshBone** [comment]
> I still get a yellow message on submission, though it disappears both times before I could read it, and the email notification says that file location was not provided.

The yellow popup is just a notification, that the file was uploaded successfully... If you don't like it, I can get rid of it. Email notification... It won't be displayed once I'll figure out the e-mail digesting mechanism.

**Comment by Gyukat** [comment]
Shouldn't it be green, if it is success!

**Comment by Gyukat** [comment]
Still need to make the file message green.

**Comment by JoshBone** [comment]
I've made the message green...
