### ISSUE TITLE
Documentation links

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#14]
Need links to documentation

- Main link from the side
- Specific links from the Report Forms (new record/edit)

**Comment by JoshBone** [comment]
Please check...

**Comment by Gyukat** [comment]
I see the main link...are there dynamic links from various fields as well?

**Comment by JoshBone** [comment]
Dynamic links are on the top of the form panel (the question mark icon). 
I can only drop you to a specific place if the documentation includes an anchor tag for that section.

**Comment by Gyukat** [comment]
Well, there are anchors that are more detailed per section...so you could put them next to fields...sometimes two fields would have one link...but better than nothing.

**Comment by JoshBone** [comment]
Can I ask you a favour, to prepare a list of fields with their respective deqar docs links? I can put them in a config file then and then it could be corrected in one central place later...
You can type it here in the format of:
`field : url` (like: `agency : https://docs.deqar.eu/data_submission/#report-creation`)

**Comment by Gyukat** [comment]
Okay, I am just updating the manual as well so it is a good moment to do the whole thing...will try by end of day, but tomorrow definitely.

**Comment by Gyukat** [comment]
Don't close this...we still need it.
