### ISSUE TITLE
Filters in Menus should be "inter-dependent"

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#15]
- Eventually design drill down filters so that they are dependent on each other.  You should only get options available on the current list.

**Comment by JoshBone** [comment]
Hi Katie,

Sorry that it took too long, but I've tried to come up with a new way of filtering a table. I think it's pretty fine. Please test if you like it (the filters are also inter-dependent) and I'll implement for all the table-views. Currently you can see it here: https://admin.test.deqar.eu/reports

Let me know how it feels/seems.

**Comment by Gyukat** [comment]
I still can't see this...

**Comment by Gyukat** [comment]
Wait, I found it...okay, so it looks good!  I haven't test the full functionality, should I do that or can I assume that you kept it like the previous.  We would need to add an ID filter...and the label "active" should probably read "valid only" or "currently valid".

**Comment by Gyukat** [comment]
Btw, I assume you will move it also into the MyReports

**Comment by Gyukat** [comment]
Btw, the interdependence rocks!  :)
