### ISSUE TITLE
Administrative Functions for agencies/admin

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#16]
For agencies/admin:

 - There should also be a chance when saving the edited record to attach a "note" on the entry.  (This could be saved as part of the record history entry.)
 - There should be some place to request deletion at the bottom of the edit record.  I guess it should trigger a generic red flag with a note.  An email or alert should be sent to administrators. 
 - There should be some place to signal a problem with a record. I guess it should trigger a generic yellow flag with a note attached.  An email or alert should be sent to administrators. 

For admin:

- Where can I deactivate flag?
- Should have admin rights to edit all records in the Records menu.

**Comment by ctueck** [comment]
All covered.
