### ISSUE TITLE
Put the Number BACK!

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#17]
Hey Josh, we had all the drop-downs, including for activities, status and decision with the ID numbers next.  It really helps when someone is filling out the CSV to have those numbers also in the Manual UI drop-down lists.

**Comment by JoshBone** [comment]
Just a suggestion/question. Don't you rather want to have a list under Reference data with these values? You can call it CSV Cheat Sheet or something... I think if you never fill in the CSV just using the web API these values are super weird looking.

**Comment by JoshBone** [comment]
Please check...

**Comment by Gyukat** [comment]
I found it useful in the list itself...I think that for the activity it is in any case useful to include the number in parentheses after the activity name.  For the decision and status, if you really insist on keeping them out, then include these in the Documentation that you dynamically link to the form:fields.

**Comment by Gyukat** [comment]
Btw, I am not really sure what you want me to check...is there somewhere I can see the results of the code?

**Comment by Gyukat** [comment]
I have checked....so, the format in the grey boxes in unclear.  Can we do something like this:

Status/Decision:
1 - part of obligatory EQA system
2 - voluntary

1 - positive
2 - positive with conditions
3 - ...

For the activity IDs: 
institutional accreditation - ID 235
programme evaluation - ID 004

Thanks!
