### ISSUE TITLE
Make values in the View Record Cut/Paste

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#18]
Especially in the Institution Records, people will want to cut and paste the DEQARINST or ETER IDs, but I can imagine that they will need for other things as well.

**Comment by Gyukat** [comment]
doesn't work for me yet....seems the same...

**Comment by JoshBone** [comment]
<img width="584" alt="Screenshot 2019-04-14 at 15 23 23" src="https://user-images.githubusercontent.com/927344/56093462-59d3c900-5ec9-11e9-809e-848c0f0d492a.png">

Should work for all types of fields...

**Comment by Gyukat** [comment]
Does not work for me...tried under reference data reports and my data reports.

**Comment by JoshBone** [comment]
Okay got it... 
Firefox treats disabled fields differently. I've set the fields readOnly rather. This way should work fine. (I've tried in both.)

**Comment by Gyukat** [comment]
It works!!!  Close :)
