### ISSUE TITLE
Institution Module

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#22]
Here are the wireframes for the Institution Module.  

![Institution Standard Webform_2019-04-15](https://user-images.githubusercontent.com/33084539/56310072-3455f200-614b-11e9-8d7c-b6d8bafc7acf.jpg)

**Comment by Gyukat** [comment]
There are four wireframes:

- the first is generic to show the basic functionalities and features with all elements included
- the second in the general New Record entry view for both agencies and administrators with only slight differences in functionality.  (I also showed all features expanded in this view.)
- the third is view/edit mode for administrators
- the fourth is view/edit mode for agency users

So, notes to support:

- transliterated form, you may want to check to make sure it is roman alphabet...not sure if this is easy or hard
- for the website, we should probably find a way to ensure that it is a URL, but we may also consider some sort of check to see if the URL is a base domain name.
- For Local ID pop-up, the administrator would receive a full drop-down of all agencies, whereas for an agency, it should be the agency automatically.  For a submitter like GAC, there might still be a drop-down.  Importantly, there can only be ONE agency local ID for an institution for each agency.  So, once they have entered the single one, the button should not be available to them anymore.  (This is more for the edit options.)
- We should make sure that the same country is not entered twice...unless a different city is entered.
- NEW FIELDS!  I have added a local identifier note field (not in data model)
- NEW FIELDS!  I have created a drop-down institution relationship for the hierarchical links.  This is because 1) the source/target will depend on the record where the user has come from AND 2) we have decided to create types of hierarchical relationship, not currently possible in the data model.
- IMPORTANT!  We have decided to let agencies create not only records, but also historical and hierarchical links and historical names. HOWEVER, we would like to flag any record where an agency has  added this information for us to check.  It can be a yellow flag called "agency added historical or hierarchical data."  This would allow DEQAR staff to check what they have done

**Comment by Gyukat** [comment]
Okay, the same two wireframes with two additional...

![Institution Standard Webform_2019-04-15](https://user-images.githubusercontent.com/33084539/56305697-fe137500-6140-11e9-9b89-6cb763f0e5d5.jpg)

**Comment by Gyukat** [comment]
So additional notes:

- We discussed with Colin and for institutions we do NOT need to separate VIEW/EDIT.  In fact, the agencies cannot edit very much once the record has been created...see the fourth wireframe.  They can add additional alternative names, add or delete a single local ID, and/or flag the record to request other changes.  The admin can just view all the fields as editable, see third wireframe.
- For agency VIEW/EDIT local ID, you will have EITHER the ADD button OR a deletable value already there.  Basically, agencies can see all other local IDs, but can only add/delete their own.  They can only have one.
- For all exact dates, you can use your handy-dandy calendar feature.
- For institution selection on linked hierarchical or historical records, we can use the same feature that we use for institution selection in report records.
- Needless to say that all ETER records are already "created" and so cannot be edited by agencies--except for adding alternative name, local IDs and/or flagging.  In the case of ETER/OrgReg records, the source notes for former names, historical/hierarchical relationships can be automatically be stamped in the notes fields, as they are in the Django Suite.  
- The record creator should also be mentioned in the "record information"...so under record history, we will see that a record was from ETER/OrgReg.

**Comment by Gyukat** [comment]
Managing Records:

- As we know the management of records, including internal notes, source notes, flagging and time stamping of events is especially important for Institution records.
- Flags: 
   - There are not really many automatic flags for institution records.  The only one I can think about is if no QF level information is provided.  This should be a yellow flag.  NOTE! Any other flag we are giving to institution records should be given to report records.  
  - It is, however, REALLY important to have the possibility to manually flag an institution record in order to request change (yellow flag) or deletion (red flag).  I have added a pop-up for flagging (ala all the others we have created).  The pop up should include a choice to "request for deletion" or to "request change or addition".  In either case, the user should be given a chance to leave details or an explanation in a comment field.  
- Record History Event Stamping: whenever the record is edited by the end user or administrator, they should be presented with a dialog box upon submission.  This should allow them to put an optional short note indicating change or addition made.  In this case, the record information will include, basic event (e.g. "update", date stamp, user, and short note).  We can capture the source of much of the information that is changes or added through the record history
- Internal note: gives the possibility to administrators to explain why flags have been dropped or other aspects of the record management.  This is in contrast to the Comments field which is for agencies to describe features of the institution itself, its structure or aspects of its QA. 
- Source notes: the source of the record and most updates should be recorded as part of the record history details (see above). The source of the historical/hierarchical information and historical names will be autostamped when it is ETER/OrgReg.  Otherwise, the Admin staff can enter manually in the fields provided.  I have added the same sort of fields for local IDs for agencies to include notes (for instance if they use a national Identifier or a shared system).

**Comment by Gyukat** [comment]
We have created institution hierarchical link "types".  We should make sure to implement these in the administrative interface.  (On the public UI these types will determine how the relationships will show up in results lists.)

**Comment by Gyukat** [comment]
INSTITUTION LIST:

- when multiple countries, you lack a divider between the values **DONE**
- "institution" field should be made up of several values: primary institution name / official institution name [if different from primary] (acronym [if exists]); include all these values in the filter. **DONE**
- include "city" as well in a new column after country; and add a filter. **DONE**
- field "DEQAR ID" should be labelled "DEQARINST ID" (DEQAR ID is the report ID); the filter label should be updated as well **DONE**
- "filter by institution/programme" should just read "filter by institution" AND should act that way as well...programmes are for report records. **DONE**

**Comment by Gyukat** [comment]
Josh, we just spoke with Colin.  The ADD NEW INSTITUTION BUTTON should be available only for Admin.  **DONE**

Instead of having manual entry available to agencies, we are simply going to ask people to fill in the HEI template and upload ourselves.  There should probably be a similar API.

**Comment by Gyukat** [comment]
NEW INSTITUTION RECORD: 

- Transliteration should not show, but should be a link/button below the official name field, which opens a new field.  (See first wireframe above) **DONE**
- Same for Alternative Name...should be a link/button.  (See first wireframe above) **DONE**
- Local ID pop up did not work. **DONE**
- Historical pop up should include only "Institution Name" in the label AND "DEQARINST ID" should be included in the field instruction. **DONE**
- Hierarchical pop up, you cannot delete the name in order to replace with another. **DONE**
- In general, I am going to have to test the dates for founding and closing and historical and hierarchical...there are all sorts of possible problems, but it will take a dedicated test session.
- Warning message for "founding year" and "closing year" date switch is: Valid from is later date, then valid to >> should read "founding year is later than closing year" **DONE**
- Btw, the original message is incorrect English...it should read "Valid from date is later **than** valid to date"...I suppose that should be updated on the Report form in multiple places.
- After you have created an institution you should either taken to the record that was created OR to the list which shows the record that was created...as it stands, you never see the record you made.

**Comment by Gyukat** [comment]
INSTITUTION LIST:

- SORT:
   - The "sort" function doesn't work for: DEQARINST, country, city **DONE!**
   - "ETER ID" sort puts the numbers in a strange order...maybe it is alphabetic? **DONE!**
<img width="81" alt="Screen Shot 2019-09-29 at 15 47 05" src="https://user-images.githubusercontent.com/33084539/65833410-72e20200-e2d0-11e9-81c3-092477d6c17f.png">
<img width="1060" alt="Screen Shot 2019-09-29 at 15 48 31" src="https://user-images.githubusercontent.com/33084539/65833434-a886eb00-e2d0-11e9-850a-f344250df855.png">

  - "Institution" sort has problems..it treats different "" <<>> etc. differently, probably should just ignore...also has two names at the end... **DONE!**
- FILTERS: 
   - order of filter fields should reflect list order; institution name can be shorter field. **DONE!**
   - the ETER ID and DEQARINST ID filters don't work the same...DEQARINST ID works better, except that it doesn't allow you to enter the term DEQARINST.  That should be fixed.
- LIST: 
   - the country and city fields should wrap rather than cut the text. **DONE!**

**Comment by Gyukat** [comment]
INSTITUTION EDIT (admin):

- Add Transliteration button too close to next field and not able to make it go away if you mistakenly open it.  Should act more like "Alternative Name"...I think it should be a link not a button...it is really rarely used.
- Institution Former Name should have some validation.  It let me add two different records with the same valid to date.  This should not be possible.  I think the button should be "Add previous name set" to not mislead. _we can discuss_
- Do not give suggestions for webpage!!!  It should be a unique value!
- Local ID pop-up still doesn't work.
- With multiple countries, do not put the country city labels above the additional fields...just once at the top.
- Make QF-EHEA levels like "languages" in the Reports File...takes up too much space and doesn't need a linked value!!!
- When I leave the record and have not saved or closed, I lose everything...it should not let me leave the record (for ANY edit view)
- Admin should not "Request deletion".  Admim should either "accept deletion/delete" or "override deletion"...there should be a dialog box with note for the second possibility.  Basically, flags and deletion should be similar for admin...we can "override flags" as well, but should have a dialog box with note possibility for that as well. _maybe I will make a record for flags and deletion_

**Comment by Gyukat** [comment]
Other:

- Remove all "x" from forms and subforms on institutions.  Leave just the close button on the LEFT side.
- DEQARINST should be added to the domain of hierarchical and historical institution "searches" and links.  It should also be listed with the ETER ID in the names dropped down...and on the instructions in the box.

**Comment by Gyukat** [comment]
INSTITUTION/AGENCY VIEW:

- This should not be editable!!!!  Only view and request deletion for now.

**Comment by JoshBone** [comment]
> The "sort" function doesn't work for: DEQARINST, country, city

I've corrected it for DEQARINST. 
As for country and city, since these can be multiple values, you can't sort based on them.

**Comment by JoshBone** [comment]
> ETER ID" sort puts the numbers in a strange order...maybe it is alphabetic?

**Done!**

**Comment by JoshBone** [comment]
> order of filter fields should reflect list order; institution name can be shorter field.

**Done!**

**Comment by JoshBone** [comment]
> the country and city fields should wrap rather than cut the text.

**DONE!**

**Comment by JoshBone** [comment]
> the ETER ID and DEQARINST ID filters don't work the same...DEQARINST ID works better, except that it doesn't allow you to enter the term DEQARINST. That should be fixed.

How should it work. 
ETER: If I search 01 should it give back all the 0001 ETER ids?

**Comment by Gyukat** [comment]
i  think that is how DEQARINST works, right?  It is okay...

**Comment by gygabor** [comment]
Add Transliteration button too close to next field and not able to make it go away if you mistakenly open it. Should act more like "Alternative Name"...I think it should be a link not a button...it is really rarely use

**Comment by gygabor** [comment]
> Add Transliteration button too close to next field and not able to make it go away if you mistakenly open it.  Should act more like "Alternative Name"...I think it should be a link not a button...it is really rarely used.

Done.

**Comment by gygabor** [comment]
> With multiple countries, do not put the country city labels above the additional fields...just once at the top

Done.

**Comment by gygabor** [comment]
> Remove all "x" from forms and subforms on institutions. Leave just the close button on the LEFT side.

Done.

**Comment by gygabor** [comment]
> When I leave the record and have not saved or closed, I lose everything...it should not let me leave the record (for ANY edit view)

It works only on the Institution Form. I'll fix the other forms tomorrow.

**Comment by gygabor** [comment]
> Make QF-EHEA levels like "languages" in the Reports File...takes up too much space and doesn't need a linked value!!!

Done
