### ISSUE TITLE
Agency module

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#23]
Three views:

- generic
- administrative view with sample values
- agency view

![Agency Standard Webform_2019-04-26](https://user-images.githubusercontent.com/33084539/56828152-fa7a9f00-6860-11e9-84dd-c2c675fd0806.jpg)

**Comment by Gyukat** [comment]
I will stick in some notes later...but hopefully most of this is intuitive.  I have added a flagging module similar to the reports/institutions module.  

In general, agency users have very little that they can change, and only in their own record. They CANNOT create a new record.

**Comment by Gyukat** [comment]
Comments on Agency List:

- Make the ID linked to the record too...in addition to the agency name...and heck just do the acronym as well.  They are all unique to the record.  (This is mainly for consistency with reports.) **DONE**
- Check alphabetisation of agency names...a bit wonky.  You seem to have two problems--lack of stop words and also treatment of acronyms. **DONE**
- Report validity date sort is based on first day, while agency is based on last date.  We should probably be consistent or change labelling.  We can check with Colin to see which he would prefer. **DONE**
- Filter by country drop down should only list countries actually in the domain. **DONE**

**Comment by Gyukat** [comment]
Comments on Agency Record/Agency Name:

- Agency Name pop up: we need to number the "sets" of name or somehow group the field.  So, one group = name/transliteration/acronym/transliteration.  This was already done in the wireframe through the labelling, which was much simpler.  
- Agency Name pop up: The way to add and edit current names should not be separated.  There should just be a single pop up for current names.  The Administrator has full access, the Agency User can only add non-primary "additional" names. 
- Agency Name Current: originally it was intended to show all current names on the main form.  These should not be linked to anything but simply listed.  The update button took you to the current name pop up.
- Agency Names Past: for this, you should show one entry per past record.  Each of these is linked, and there is an Add button so you can create another past "cluster" of names if needed.
- Agency Name Primary: I think to make this even clearer, you could remove the first field and simply make the primary name the first current name.  You could put a star on the primary or simply make that the linked term (if you didn't want to use an Update button).

**Comment by Gyukat** [comment]
Functionality problem with names:

- You should never be able to have two primary names on any one pop up.  For example, current names should only have one primary name and one primary acronym.  They do not have to be paired (which is why we put a check box on all fields.
- I tried this and it let me put two primary acronyms.  I would expect it to validate as I close the pop up.

**Comment by Gyukat** [comment]
Validity:

- I checked the dates with a bad order, and that worked well.  
- However, we should ask Colin whether it should really be possible to put an earlier validity end and still have an agency registered.  I think this happens for a short time, but we would probably need at least a message to signal that there is a discrepancy between validity dates and registration status.  Maybe this can be an alert like..."The validity date has expired but this agency is still listed as registered."

**Comment by Gyukat** [comment]
Activity:

- We should actually just list all the information...otherwise, it just looks weird.  So, on the main form show: 
<ActivityType> "-" <Activity Short Display> 
new line <Activity> 
  It will make the entries longer, but at least clear.   
Right now I am seeing this:
<img width="511" alt="Screen Shot 2019-08-11 at 18 34 01" src="https://user-images.githubusercontent.com/33084539/62836743-a5736500-bc66-11e9-950e-c47c88efc31b.png">

- If there is a valid to date and it has passed, then you can just write "expired" before or after the entry, ideally in red or pink.
- Expired activities should go at the end of the list.  Activities can otherwise list by type: institutional, institutional/programme, programme, joint programme, 
- The activity pop-up is locked for me...that should only be the case for Agency Users.  (I will wait for you to unlock it before I test this form.)

**Comment by Gyukat** [comment]
So, funny thing...I was using the PKA record to do all my testing, and now it has completely disappeared from the test system.  Can you figure out what happened?  Is it in some twilight zone or did I actually expunge it from the system with something that I did.

**Comment by Gyukat** [comment]
Focus Countries:

- It let me add the same country twice.  Again, this is something that should be stopped when I close the pop up.  In general, the pop-up should be checked for validity.

**Comment by Gyukat** [comment]
Validation: There is a bigger validation question...basically, the registration dates, focus countries and activities should not be able to be deleted if this violates the data relations (i.e. if the focus country or activity is already from a report OR if a report has been uploaded for that period registration period by the agency). 

In these cases, you can create a "valid to" date if you want to halt the activity or country or agency status, but you should not be able to violate the data structure by deleting or changing the value.  

(We can ask Melinda about the names of activities and how stable these are...maybe these could be edited, but countries and registration dates...I don't see it.)

**Comment by Gyukat** [comment]
When I changed and submitted the agency record, it kept me in the edit view.  Really confusing...

In this case, some of the data "stuck" in the fields, but for instance the added phone number just seemed to disappear.

**Comment by JoshBone** [comment]
I've put Agencies to Solr as well to be able to 'live filter' the dropdowns. I've added focus country just because I thought it could be interesting. :) More to come...

**Comment by JoshBone** [comment]
> * You should never be able to have two primary names on any one pop up.  For example, current names should only have one primary name and one primary acronym.  They do not have to be paired (which is why we put a check box on all fields.

I need a bit of help with this one:

- So if the user presses Update button with 'Primary names / Acronyms' should be there an empty form, or one with the current primary name?
- If the user updates the data (press Update Name button) the previous entry should be overwritten or it should go to the list of former names with the timestamp for valid_to?

**Comment by Gyukat** [comment]
BASICALLY, I THINK THE WHOLE AGENCY RECORD SHOULD BE DISCUSSED A BIT.

**Comment by Gyukat** [comment]
Melinda's comments AGENCY RECORD:

- Label "Register" read "Admission on the Register"
- Also we should probably we have a condition here. If the date of registration expires a notification is sent to EQAR  and perhaps also to the agency (Colin what do you think?) _for notifications!_
_Considering the state of suspended entries shouldn’t we have an extra option somewhere here? Perhaps even when agency’s submit an appeal? (question for Colin how to put it)_
- Need suggestion/instruction on how to put the phone number format i.e. + (country code) 123 456
- Contrasting colour scheme: I find it rather difficult to view the different fields. I must say it’s better on my laptop, but the separation is completely invisible on my computer screen (using both chrome and firefox). Perhaps a bit more contrast, (having the writing in black instead of grey would improve a bit the visibility).
- focus country: there is a long long list if an agency works in more than 5 countries. Would it be possible to create two, or tree columns so it doesn’t go down for ages.
- would it be possible to export the registration information for the agencies that want it. We often get requests that they need ‘official’ proof that they are on the register :). _This is for later...reporting_
- the "View public record" on EQAR appears if I click on show info. I find it would be great if we can have this button on top unhidden, easy to click so one can check the changes to the profile immediately. _If so, then we should do it for all three record types..._
- **(more important, we should update the link on the Report record so that it brings us to the report and not the institution record!!!)**
