### ISSUE TITLE
Report list problems

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#28]
EKKA just tested our new manual report submission interface, and they didn't notice the possibility to edit records.  We discussed and have a few possible suggestions. 

- We noted that it is not logically consistent to have the link from the institution/programme field to the report.  We should consider linking from the DEQAR ID rather than the institution/programme names to be clear that you are viewing reports...**DONE**
- We thought the header for the View Reports record could be View&Edit Reports as this is the path that takes you to the editting possibility.  **DONE**
- We thought that the record info could be "hidden" by default so that the buttons at bottom are visible on more screens. **DONE**

These are just thoughts, SO if you have more elegant solutions, we are open to suggestions.

**Comment by Gyukat** [comment]
More thoughts on MY Report List:

- You should include the Local IDs along with the DEQAR IDs in the following way "DEQAR ID / Local ID", also in the label and filter box.  
     - The sort can be by DEQAR ID, but the filter should allow you to enter the local ID as well.  This would mean that the filter should allow parts of the string (perhaps with some criteria ala institution names).
- When there is no "valid to" date, then it is unclear what the single date means...i.e. end users do not know if it is a valid from or a valid to.  We need some notation that makes it clear that it is the valid to missing.  Maybe "<date> to <date>".  In this case a missing valid to could look like "<date> to  " or "<date> to n.a."  We would be happy for your ideas as we don't feel like we have a good solution. **DONE**
- p.s. I like the filter by agency as a solution for submitters...this means that we don't need a separate column for agency I guess...clever.

**Comment by Gyukat** [comment]
More thoughts on Reports list:

- Label "Activity" should read "Activity Type" on this list.  **DONE**
- AS ABOVE, when there is no "valid to" date, then it is unclear what the single date means...i.e. end users do not know if it is a valid from or a valid to. We need some notation that makes it clear that it is the valid to missing. Maybe " to ". In this case a missing valid to could look like " to " or " to n.a." We would be happy for your ideas as we don't feel like we have a good solution. **DONE**

**Comment by Gyukat** [comment]
In general, there is one layer of grey padding around everything that seems unneeded...any way to remove it?  This would fill the space more nicely... **DONE**

**Comment by Gyukat** [comment]
MyReports: all the dates say "Invalid date"...don't know why. **DONE**

Reports: still says "Activity" instead of "Activity Type" in the column. **DONE**

Both: on the filters validity, I think "Active" should read "Current" **DONE**

Functionality: DEQAR ID doesn't sort. **DONE**

Basically, everything in the string above is still a problem.

**Comment by JoshBone** [comment]
> You should include the Local IDs along with the DEQAR IDs in the following way "DEQAR ID / Local ID", also in the label and filter box.
The sort can be by DEQAR ID, but the filter should allow you to enter the local ID as well. This would mean that the filter should allow parts of the string (perhaps with some criteria ala institution names).

This is the only one left.

**Comment by JoshBone** [comment]
> You should include the Local IDs along with the DEQAR IDs in the following way "DEQAR ID / Local ID", also in the label and filter box.
The sort can be by DEQAR ID, but the filter should allow you to enter the local ID as well. This would mean that the filter should allow parts of the string (perhaps with some criteria ala institution names).

Can you check on MyReports if it's suitable like this?

**Comment by Gyukat** [comment]
- The ID sort is not in numerical order but in alphabetical (i.e. 1, 10, 1000, 2, 20, etc.);  it should be numerical. **DONE**
- Format for both the validity and for the IDs is not my favourite.  
    - IDs: it looks like it is one number.  In the very least you should not include the local ID in the link.  This will separate it more clearly from the DEQAR ID.  Maybe if you disappear the link and add parentheses to the local ID this will work.  (In that case, you should also add parentheses to the label.) Do you have other ideas about how to better separate?  
    - Validity: I think you still need the word "to " in between the two dates, even when you put "N.A."
- Btw, the view+edit breadcrumb is good, but I still think the edit should return you to the view record after you submit.  (From there you can go back to the list.)

**Comment by Gyukat** [comment]
Interestingly, the filter works different for the Local Id and the DEQAR Id.  For Local ID, you can put the beginnings of numbers and it finds them...for DEQAR Id, you need the whole number.  I prefer the way you did it for Local Id. **DONE**

**Comment by JoshBone** [comment]
> Validity: I think you still need the word "to " in between the two dates, even when you put "N.A."

Something like this?
<img width="1239" alt="Screenshot 2019-08-14 at 16 22 37" src="https://user-images.githubusercontent.com/927344/63028912-edd19380-beaf-11e9-9f61-ca32ad6e7d0b.png">

**Comment by JoshBone** [comment]
> IDs: it looks like it is one number. In the very least you should not include the local ID in the link. This will separate it more clearly from the DEQAR ID. Maybe if you disappear the link and add parentheses to the local ID this will work. (In that case, you should also add parentheses to the label.) Do you have other ideas about how to better separate?

**What about this?**

<img width="1211" alt="Screenshot 2019-08-14 at 16 44 46" src="https://user-images.githubusercontent.com/927344/63030676-ff686a80-beb2-11e9-9f08-9938d76ff53d.png">

**Comment by JoshBone** [comment]
I've put them to admin test for checking...

**Comment by Gyukat** [comment]
Report List: activity type has been added to the list, but it is NOT populated!!!!

> > Validity: I think you still need the word "to " in between the two dates, even when you put "N.A."
> 
> Something like this?
> <img alt="Screenshot 2019-08-14 at 16 22 37" width="1239" src="https://user-images.githubusercontent.com/927344/63028912-edd19380-beaf-11e9-9f61-ca32ad6e7d0b.png">

Yes, nice

**Comment by Gyukat** [comment]
> Btw, the view+edit breadcrumb is good, but I still think the edit should return you to the view record after you submit. (From there you can go back to the list.)

So, basically, when you are editing a report records and you EITHER "close" or "submit", please return the user to the VIEW of the same record.

**Comment by Gyukat** [comment]
Still need to figure out how to get submitter and agency access to check a lot of this...

**Comment by Gyukat** [comment]
> > IDs: it looks like it is one number. In the very least you should not include the local ID in the link. This will separate it more clearly from the DEQAR ID. Maybe if you disappear the link and add parentheses to the local ID this will work. (In that case, you should also add parentheses to the label.) Do you have other ideas about how to better separate?
> 
> **What about this?**
> 
> <img alt="Screenshot 2019-08-14 at 16 44 46" width="1211" src="https://user-images.githubusercontent.com/927344/63030676-ff686a80-beb2-11e9-9f08-9938d76ff53d.png">

This seems fine!  Can't check it live yet.
