### ISSUE TITLE
Rights/functionality for different users

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#34]
Administrator:

- Should not have “MyData”.  **DONE**
- Should have be able to addnew/view/edit/flag/delete all records through “ReferenceData”. **DONE**
- Report records do not BELONG to the administrator, but to the owning agency.
      
Submitter:

- MyReports include all report records they have submitted; they can view/flag but not edit these records
- MyAgencies should include a list of all agencies for which they submit.  These can be linked to view/flag agency records. **DONE**
- Report records do not belong to the submitter but to the owning agency; submitters CAN overwrite records by resubmitting in bulk. 
 
Agency:

- Owns all records submitted on its behalf by Submitter or Administrator; has addnew/view/edit/flag rights. **DONE**
- MyReports include all report records submitted by the agency a proxy or an administrator. **DONE**
- MyAgencies includes a direct link to own record. **DONE**

If an agency is also a submitter, these may be mixed.  In this case, some records may be editable while others are simply view only.  

View only records for Submitters should be shown using "deactivated" edit button with mouseover saying "As a submitting agency, you do not have the right to edit this record.  This record can be edited by the creating agency."

**Comment by JoshBone** [comment]
> MyAgencies should include a list of all agencies for which they submit.  These can be linked to view/flag agency records.

So only viewing is allowed for "umbrella" agencies?

**Comment by Gyukat** [comment]
Yes.

**Comment by Gyukat** [comment]
> So only viewing is allowed for "umbrella" agencies?

They can also flag records, right?  So, viewing and flagging...including flag to request deletion.  If they want to update a record, they can resubmit.

**Comment by JoshBone** [comment]
Hmm... 

So far there were no options for creating flags, only request deletion. Is this new? (This function only existed for institution records). 

If I make the edit button disabled, that means that they can't click on it and they can't go into the edit form where they can request deletion. How should we overcome this? Should I put Request deletion to the view form in this particular case?

**Comment by Gyukat** [comment]
ugh...we should probably discuss to envision the whole workflow for each user type and record type.

**Comment by Gyukat** [comment]
Okay, agree.  YOu can put the request deletion on the view form.  

Question: will this also be the case for the creating agency?  Will it work this way under the Reference/Reports as well as MyReports?

**Comment by Gyukat** [comment]
Basically, besides the creator and submitter, noone else should be able to request deletion.

**Comment by Gyukat** [comment]
Administrator:

- Should not have “MyData”.  **DONE** - _okay (now I can't check anything :( )_
- Should have be able to addnew/view/edit/flag/delete all records through “ReferenceData”. **DONE** >> _can we flag or delete records???  I only see the possibility to request deletion even for administrators!  I think we should be able to flag problems and also to simply delete a record.  We can remove flags at the bottom, but the problem that was identified should also be recorded in the history NOT just the level of the flag_
- Report records do not BELONG to the administrator, but to the owning agency.
      
Submitter:

- MyReports include all report records they have submitted; they can view/flag but not edit these records _can't check.  flag should be "request deletion"_
- MyAgencies should include a list of all agencies for which they submit.  These can be linked to view/flag agency records. **DONE** _can't check_
- Report records do not belong to the submitter but to the owning agency; submitters CAN overwrite records by resubmitting in bulk. 
 
Agency:

- Owns all records submitted on its behalf by Submitter or Administrator; has addnew/view/edit/flag rights. **DONE** _I think we agree for request deletion rights for record rather than "flag"_
- MyReports include all report records submitted by the agency a proxy or an administrator. **DONE** _can't check this..._
- MyAgencies includes a direct link to own record. **DONE** _can't check this..._

If an agency is also a submitter, these may be mixed.  In this case, some records may be editable while others are simply view only.  _may want to separate these on the list._

View only records for Submitters should be shown using "deactivated" edit button with mouseover saying "As a submitting agency, you do not have the right to edit this record.  This record can be edited by the creating agency."
