### ISSUE TITLE
Record Headers

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#35]
I realise that in most of our records (in contract to our lists), the IDs don't really feature.

I wonder if you could put the ID of the record:

- Agency ID
- DEQAR ID
- DEQARINST ID

at the top of the record, after View & Edit (Or Edit).  It could read:

- Reference Data » Reports » View & Edit : DEQAR ID 3998
- Reference Data » Agencies » View : Agency ID 38
- Reference Data » Institutions » Edit : DEQARINST ID 5803

Finally, not exactly a header issue, but kind of goes with this.  In the Activity List, please put the Activity ID as the first column.  This replicates better the other lists. The rest can remain as is.

**Comment by Gyukat** [comment]
This looks good...both the breadcrumb and the activity list.

**Comment by ctueck** [comment]
As discussed, very fine as it is now.
