### ISSUE TITLE
Report record: show info

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#41]
The record creation does not list in chronological order with the changes.  It stays at the bottom while new changes are added just above it.  It should be at the top.

If a record has "no flag", then there should be NO flag deletion possibility.

**Comment by JoshBone** [comment]
> If a record has "no flag", then there should be NO flag deletion possibility.

I don't think there is a possibility for deletion in that case.

**Comment by Gyukat** [comment]
There is an “x” next to the green flag.

**Comment by JoshBone** [comment]
on report form?
