### ISSUE TITLE
INSTITUTION Testing

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#54]

**Comment by Gyukat** [comment]
PROBLEMS NOTED: 
- **DONE!** when you go from VIEW to EDIT it gives you a dialog box about saving changes.  Not needed.
- **DONE!** missed DEQARINST and ETER IDs from form
- **DONE!** missed CITY label
- **DONE!** LOCAL ID should be specific to agency using
- **DONE!** NATIONAL ID should probably be OTHER ID.  We would need string qualifier then, that could be displayed on the main form.

**Comment by JoshBone** [comment]
> when you go from VIEW to EDIT it gives you a dialog box about saving changes.  Not needed.

That was already removed from the view menu. Still works on edit though.

> missed CITY label

City field goes together with Country. If you add a new field, it will display a placeholder 'Enter City name'. Should we label it differently (Countries with City)?

**Comment by JoshBone** [comment]
> LOCAL ID should be specific to agency using

I've set this field to be the same than on the report form. So those agencies can be selected under which I can submit.

**Comment by Gyukat** [comment]
> > when you go from VIEW to EDIT it gives you a dialog box about saving changes.  Not needed.
> 
> That was already removed from the view menu. Still works on edit though.  

I should work in Edit, no?

> 
> > missed CITY label
> 
> City field goes together with Country. If you add a new field, it will display a placeholder 'Enter City name'. Should we label it differently (Countries with City)?

You can call the whole field "Location*".  Then the in field instructions can be "Please select country" and "Please enter city name."  (I think that this is clearer anyways as two cities in the same country would still require the same country twice...so it is not really a unique country , but a unique location in each row.

**Comment by Gyukat** [comment]
> > LOCAL ID should be specific to agency using
> 
> I've set this field to be the same than on the report form. So those agencies can be selected under which I can submit.

So, it will open with a view specific to the user, I guess.

**Comment by Gyukat** [comment]
- In breadcrumb, put the name of the university...either just primary name or multi display as in the menu list.

**Comment by Gyukat** [comment]
**DONE!** Same problem when I try to edit the institution "some error on your form" even when I replace the former value.

**Comment by Gyukat** [comment]
**DONE!** - when I push the "add alternative name" button and then leave blank, it says that the field is required.  It needs a different alert message. Similar problem to agency record.
<img width="536" alt="Screen Shot 2020-08-10 at 20 55 58" src="https://user-images.githubusercontent.com/33084539/89819650-15534e80-db4c-11ea-867e-cbc72b85c021.png">

**Comment by Gyukat** [comment]
- on Add former names subform, there is a problem with the required date field...it doesn't notice when the information has been entered properly.
<img width="515" alt="Screen Shot 2020-08-10 at 21 00 23" src="https://user-images.githubusercontent.com/33084539/89820017-99a5d180-db4c-11ea-885d-b88fbaef4dcb.png">

**Comment by Gyukat** [comment]
**DONE!** - Please display the QF levels in the right order short, first, second, third.

**Comment by Gyukat** [comment]
**DONE!** - when closing date entered is before founding date, there is no particular error message but just the generic message.  We need to get rid of that generic message

**Plus I made the change that in every field there can be a more direct message entered (throughout the system)**

**Comment by JoshBone** [comment]
> * In breadcrumb, put the name of the university...either just primary name or multi display as in the menu list.

That's a bit problematic, because breadcrumbs are outside of the form, and the data is loaded into the form... 
I'll figure it out, but I'll skip this for now and come back to it later.

**Comment by JoshBone** [comment]
> * on Add former names subform, there is a problem with the required date field...it doesn't notice when the information has been entered properly.
> 
> <img alt="Screen Shot 2020-08-10 at 21 00 23" width="515" src="https://user-images.githubusercontent.com/33084539/89820017-99a5d180-db4c-11ea-885d-b88fbaef4dcb.png">

There is a rule here, that the date can't be in the future. I corrected the error message. Or we can get rid of it.
