### ISSUE TITLE
MANUAL REPORT SUBMISSION FORM / TESTING

### ISSUE THREAD

**Issue by Gyukat** [EQAR/deqar_frontend#57]
Report Submission/Edit: 
~~Local report ID should NOT be required!!!!~~
~~Close button on bottom left is missing of submit form.~~
- Activity IDs:
  - **DONE!** DEQAR Activity IDs should be put back next to activities in drop-down list (as they are on current version but not on test). 
  - **DONE!** Activity local IDs should also display when they are present. 
  - **DONE!** IDs should also display on the main agency page list of activities. Basically, in the admin interface, activity IDs should show on drop-down lists and in the Agency record view.
- Programme dialog box 
  - should require alternative name before allowing "Add More"...button should not be activated. (should act like current version!!!)
  - makes the alternative name required before allowing to Save; however, if you delete the fields, it is no longer required!!!! (should act like current version!!!)
  - is missing Programme Local ID field.
  - QF Levels drop-down should also include DEQAR system IDs listed next to them.
- **DONE!** Language list for Files subform is encoded incorrectly--for some entries there are squiggly characters.
- **DONE!** Request deletion module no longer functions.  Please put back as in the current admin.
- Report submission should take you to the View of the same record. 
- EDITTED record cannot be save -- receive error message below!!!!!  Really weird.

Report menu list:
- Reference/Reports is missing the qf-level information.  Cannot distinguish reports on the masters and bachelors version of the same programme record.

**Comment by Gyukat** [comment]
- had a problem with apostrophes not displaying in IAAR record, field link display name.  Tried to update and submit...got error message "There was some error on your form."  This is not a helpful message and not sure what is wrong either.

<img width="944" alt="Screen Shot 2020-07-20 at 15 29 56" src="https://user-images.githubusercontent.com/33084539/87943256-0ffb6a80-ca9e-11ea-8621-e72335a8da24.png">
<img width="1080" alt="Screen Shot 2020-07-20 at 15 29 35" src="https://user-images.githubusercontent.com/33084539/87943272-138ef180-ca9e-11ea-9e23-f5773ac128c6.png">

We should completely get rid of "some error on your form"...it does not help the end user at all.

- was able to submit "obligatory" institution which is not in country of official review.  This should be red flag, I guess.
- was able to submit institution not in country list.  This should be a yellow flag.  

Worth double check yellow and red list: 
 - Sanity checks may result in high-level flags for the following reasons:
   - Report Status is listed as part of obligatory EQA system in a country where the Agency does not have official status.
   - Defined QF-EHEA levels of an institution and one or more of its programmes do not match.
 - Sanity checks may result in low-level flags for the following reasons:
   - Report is on an institution in a country in which the agency has not previously been active.
   - Validity From date of a report is more than one year before the submission date. (NB: this check is suspended during the uploading of legacy data from each agency.)
   - Country of the Institution does not match the country of one or more of its programmes.
   - Report on an Institution in the EHEA is submitted without the QF-EHEA levels provided.

**Comment by Gyukat** [comment]
Sandbox: when you submit form, it takes you to a 404 page
![image](https://user-images.githubusercontent.com/33084539/88379570-7edd0a00-cda3-11ea-8583-b02dd0dcdb94.png)


Also interesting that we could not update all records in the Sandbox.  The below record could not be resubmitted with corrections:
<img width="997" alt="Screen Shot 2020-07-24 at 12 39 05" src="https://user-images.githubusercontent.com/33084539/88383441-d16df480-cdaa-11ea-9f52-e6cd8e677cf9.png">

But other could.  Was this due to the Red Flag?  This would be against logic.

**Comment by JoshBone** [comment]
To avoid confusion can I ask you to test things in the TEST system and not in the sandbox?

**Comment by Gyukat** [comment]
**DONE!** The URLs fields should actually check the format of the entry...before validating.

**Comment by JoshBone** [comment]
> Local report ID should NOT be required!!!!

It is not!

> Close button on bottom left is missing of submit form.

Never was. Since it's a separate menu, not coming from anywhere.

**Comment by Gyukat** [comment]
- When you SUBMIT the new or edited record, then you should receive alerts not just for successful submission but also for the flags, including the colour and the detail of the problem.
