### ISSUE TITLE
Agencies: select box in EQAR decisions

### ISSUE THREAD

**Issue by ctueck** [EQAR/deqar_frontend#61]
The drop-down for EQAR decision types appears behind other fields. (Probably a `z-index` issue?)

**Comment by JoshBone** [comment]
On which browser is this happening? 
In Chrome it seems fine for me...

**Comment by ctueck** [comment]
Using Firefox:
![image](https://user-images.githubusercontent.com/37637883/97061381-f2570900-1596-11eb-87dc-2a1d84bc929f.png)

I checked quickly in Safari, too, same there:
![image](https://user-images.githubusercontent.com/37637883/97061342-d7849480-1596-11eb-8274-bc18aa7a3e5f.png)
