### ISSUE TITLE
Countries: rich text fields don't save

### ISSUE THREAD

**Issue by ctueck** [EQAR/deqar_frontend#64]
All rich text fields (boxes) do not save changes (= same as in #60)

**Comment by ctueck** [comment]
Fields now save correctly, but somehow they got an odd look when you view a record:
![image](https://user-images.githubusercontent.com/37637883/101548464-2bfb9c00-39ac-11eb-8d7c-5211205f637f.png)
This is on Firefox. (As soon as you click edit, the toolbars look okay.)

**Comment by JoshBone** [comment]
I also noticed... It doesn't exists in test nor in my local environment. I think I have to clear the code directory and rebuild the package. Probably some old code stayed in.
