### ISSUE TITLE
Countries: national EQA requirements

### ISSUE THREAD

**Issue by ctueck** [EQAR/deqar_frontend#65]
For national EQA requirements, the popup works and changes/additions can be made, but they are lost when saving the record.

**Comment by JoshBone** [comment]
Fixed by commit: https://github.com/EQAR/eqar_backend/commit/b3317a9b33c6dc30b8ca3ed6875c876ecf1dd419

**Comment by ctueck** [comment]
Seems a new/related issue popped up: when I add a QA requirement (or a regulation), saving fails. Seems like the country ID needs to be passed in the new requirement/regulations, these are the requests & error response:

![image](https://user-images.githubusercontent.com/37637883/101549318-c27c8d00-39ad-11eb-8fd4-680e2e25ccc1.png)

![image](https://user-images.githubusercontent.com/37637883/101549402-e8a22d00-39ad-11eb-8923-f894b195c8f2.png)

**Comment by JoshBone** [comment]
Fixed by commit: https://github.com/EQAR/eqar_backend/commit/6170fde8cdbd0c3f2e20c6fcec3f698baf578f72
