### ISSUE TITLE
Agencies: self-editing doesn't work

### ISSUE THREAD

**Issue by ctueck** [EQAR/deqar_frontend#73]
Trying to edit the own agency's contact details leads to a `403 Forbidden` response:

![image](https://user-images.githubusercontent.com/37637883/102261806-80ee6380-3f12-11eb-8147-702cb0d3931e.png)

**Comment by ctueck** [comment]
Reopening this one, as there are still two issues remaining with self-editing

First, the names and acronyms (current as well as former) show as editable fields, but shouldn't be changeable by agencies themselves.

Then, only for agency website, contact person and address changes are saved. These fields show as editable (and they should be), but changes aren't saved:

- Reports by the agency
- Contact Phone
- Contact Fax
- Contact Email

**Comment by ctueck** [comment]
It seems that changes in the URL "Reports by the agency" are still not saved.

**Comment by ctueck** [comment]
Another small related issue: it would be good if the "Add Transliteration" links aren't shown when agencies self-edit, as they cannot change the name themselves.

![image](https://user-images.githubusercontent.com/37637883/122061503-de466d00-cdee-11eb-9f8d-f76b7542e40a.png)

**Comment by JoshBone** [comment]
> It seems that changes in the URL "Reports by the agency" are still not saved.

I've tried in the sandbox and it updated the URL.

**Comment by ctueck** [comment]
> I've tried in the sandbox and it updated the URL.

Logged in as you or as an agency user? Maybe it's because of a field missing in the serializer, I created an issue in the backend repo: https://github.com/EQAR/eqar_backend/issues/391

**Comment by JoshBone** [comment]
Solved by https://github.com/EQAR/eqar_backend/commit/94c5ea0e8913b71bd152a190ef88d771dc8dca19.
